# Generated by Django 4.0.4 on 2022-06-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_status',
            options={'verbose_name': 'Job_Status', 'verbose_name_plural': 'Job_Status'},
        ),
        migrations.AlterModelTable(
            name='job_status',
            table='job_status',
        ),
    ]
